import os
import stat
import sys

sys.dont_write_bytecode = True
os.environ["PYTHONDONTWRITEBYTECODE"] = "1"

HOOK_TEMPLATE = """#!/bin/sh
# Prolog Agent Toolkit Git Pre-Commit / Pre-Push Hook
# Automatically generated by prolog-agent install-hooks

echo "=== Prolog Agent Toolkit Verification ==="

if command -v prolog-agent >/dev/null 2>&1; then
    prolog-agent check-version || exit 1
    prolog-agent validate-skills || exit 1
elif command -v uv >/dev/null 2>&1; then
    uv run prolog-agent check-version || exit 1
    uv run prolog-agent validate-skills || exit 1
else
    echo "Warning: 'prolog-agent' executable not found on PATH. Skipping automated checks."
fi

echo "=== Prolog Agent Toolkit Verification Passed ==="
exit 0
"""


def install_hooks(target_dir: str = ".", hook_type: str = "pre-commit") -> int:
    """
    Install a Git pre-commit or pre-push hook in target_dir/.git/hooks/ to enforce version parity and skill validation.
    """
    target_dir = os.path.abspath(target_dir)
    git_dir = os.path.join(target_dir, ".git")

    if not os.path.exists(git_dir):
        sys.stderr.write(f"Error: Git repository directory '.git' not found in {target_dir}.\n")
        sys.stderr.write("Run 'git init' first before installing Git hooks.\n")
        return 1

    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)

    if hook_type not in ("pre-commit", "pre-push"):
        sys.stderr.write(f"Error: Unsupported hook type '{hook_type}'. Supported types: 'pre-commit', 'pre-push'.\n")
        return 1

    hook_filepath = os.path.join(hooks_dir, hook_type)

    with open(hook_filepath, "w", encoding="utf-8") as f:
        f.write(HOOK_TEMPLATE)

    # Set executable permissions (rwxr-xr-x)
    st = os.stat(hook_filepath)
    os.chmod(hook_filepath, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Successfully installed Git {hook_type} hook at:")
    print(f"  {hook_filepath}")
    print("\nThis hook will automatically enforce 'prolog-agent check-version' and 'prolog-agent validate-skills' prior to Git actions.")
    return 0
