/** <module> neurosymbolic_reasoner
 *
 * Neurosymbolic verification pattern combining LLM structured outputs
 * with pure Prolog logic constraints (CLP(Z) and dif/2).
 *
 * The LLM produces candidate symbolic statements or constraints;
 * Prolog acts as the ground-truth deterministic proof engine and validator.
 *
 * Compatible with Scryer Prolog, Trealla, SWI, and ISO Prolog systems.
 *
 * @author Doug Ransom
 * @license Unlicense
 */

:- module(neurosymbolic_reasoner, [
    verify_schedule/3,
    verify_fact/2,
    run_demo/0
]).

:- use_module(library(clpz)).
:- use_module(library(charsio), [format/2]).
:- use_module(library(lists), [member/2]).

% Knowledge Base Ground Truth Facts
kb_parent(alice, bob).
kb_parent(bob, charlie).
kb_parent(bob, diana).

kb_ancestor(X, Y) :- kb_parent(X, Y).
kb_ancestor(X, Y) :- kb_parent(X, Z), kb_ancestor(Z, Y).

%% verify_fact(+Claim:term, -Verdict:term) is det.
%  Validates a relational claim generated by an LLM against the ground truth.
verify_fact(ancestor(X, Y), verdict(verified, explanation(is_ancestor(X, Y)))) :-
    kb_ancestor(X, Y),
    !.
verify_fact(ancestor(X, Y), verdict(refuted, explanation(no_ancestor_path(X, Y)))) :-
    \+ kb_ancestor(X, Y).

%% verify_schedule(+MaxHours:integer, +Tasks:list, -Solution:term) is semidet.
%  Validates and solves task scheduling constraints proposed by an LLM within MaxHours.
verify_schedule(MaxHours, Tasks, solution(Assignments)) :-
    Tasks = [
        task(design,  2, S1, E1),
        task(code,    3, S2, E2),
        task(test,    2, S3, E3)
    ],
    % Domain: All tasks must complete within MaxHours
    [S1, E1, S2, E2, S3, E3] ins 0..MaxHours,
    % Duration constraints
    E1 #= S1 + 2,
    E2 #= S2 + 3,
    E3 #= S3 + 2,
    % Precedence constraints: design before code, code before test
    S2 #>= E1,
    S3 #>= E2,
    % Labeling: minimize overall completion time E3
    labeling([min(E3)], [S1, E1, S2, E2, S3, E3]),
    Assignments = [
        scheduled(design, start(S1), end(E1)),
        scheduled(code,   start(S2), end(E2)),
        scheduled(test,   start(S3), end(E3))
    ].

%% run_demo is det.
%  Executes a demonstration of neurosymbolic verification.
run_demo :-
    format("=== Neurosymbolic Verification Demo ===~n", []),
    verify_fact(ancestor(alice, diana), V1),
    format("1. Verification of LLM claim ancestor(alice, diana): ~w~n", [V1]),
    verify_fact(ancestor(charlie, alice), V2),
    format("2. Verification of LLM claim ancestor(charlie, alice): ~w~n", [V2]),
    format("3. Validating feasible schedule (Max 8h) with CLP(Z)...~n", []),
    (   verify_schedule(8, _, Sol1) ->
        format("   Feasible Schedule Solution: ~w~n", [Sol1])
    ;   format("   Schedule Infeasible~n", [])
    ),
    format("4. Validating tight deadline (Max 5h, requires 7h)...~n", []),
    (   verify_schedule(5, _, Sol2) ->
        format("   Schedule Solution: ~w~n", [Sol2])
    ;   format("   Schedule correctly proved Infeasible by CLP(Z)!~n", [])
    ),
    format("Neurosymbolic Demo complete.~n", []).
