% =====================================================================
% Prolog Module Template: ${MODULE_NAME} (Dialect: ${DIALECT})
% Generated by prolog-agent-toolkit
% =====================================================================

${MODULE_DECLARATION}

${IMPORTS}

%%  hello(-Greeting:chars) is det.
%   Generates a standard greeting string for ${MODULE_NAME}.
hello("Hello from ${MODULE_NAME}!").

%%  parse_item(-Item:chars)// is det.
%   Definite Clause Grammar (DCG) rule to parse an item enclosed in brackets.
%   Example: phrase(parse_item("abc"), "[abc]").
parse_item(Item) -->
    "[", Item, "]".

%%  solve_range(+Limit:integer, -Value:integer) is semidet.
%   Constraint Logic Programming (CLP) integer constraint example.
%   Constrains Value to satisfy: 0 <= Value <= Limit and Value = Limit - 1.
solve_range(Limit, Value) :-
    Value #>= 0,
    Value #=< Limit,
    Value #= Limit - 1.
